### ISSUE TITLE
Not getting all data?

### ISSUE THREAD

**Issue by NickHeiner** [NickHeiner/decomissioned-fitbit-export#1]
https://twitter.com/eramirez/status/517825406259691520

**Comment by NickHeiner** [comment]
See also; https://twitter.com/nickheiner/status/708618897470169088

**Comment by kbarter** [comment]
Any more progress on this issue?  I see that there are some recent commits, but it seems like the issue is still present.

I just downloaded my data, and there are only 1095 rows of data, when I have data points going back to 2011.

I can help in testing, just let me know what I can do.

**Comment by NickHeiner** [comment]
Yeah, the recent commits are just a UI overhaul. I haven't done anything to address this issue. I don't anticipate having much time to do so in the short term, unfortunately. You're welcome to send a PR, though! 

In the long term, I would like to fix this issue. I did [confirm](http://stackoverflow.com/questions/37090544/local-file-system-access) that this can actually be done more easily than I thought, so that helps :smile:.

**Comment by e1red** [comment]
works for me!  Thank you :+1:

**Comment by jacobeng** [comment]
I'm having the same issue - only 1095 rows of data. Is there an interim hack that could be put in place, such as tricking the query into thinking today is 1095 days ago?

**Comment by NickHeiner** [comment]
Hey -- I'm pretty sure that the problem is that the current setup just pulls as much data from FitBit as it can before the request times out. A new architecture is needed to make more requests over time to avoid the single-request timeout. This is doable but I have other projects that I'm spending time on now, so this limitation will remain in place for the foreseeable future.

**Comment by jacobeng** [comment]
Thanks for the update. If a donation would help spur some more development, please say so. 

In the meantime for others, this site can extract older data but is missing food, elevation, body weight / bmi / fat: 
https://www.squashleagues.org/fitbit/selectfitbitdata

It does seem to have heart rate and detailed sleep - which fitbit-export doesn't seem to.

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
