### ISSUE TITLE
`max` is not a supported value for time period, re: Response Code 500

### ISSUE THREAD

**Issue by uncken** [NickHeiner/decomissioned-fitbit-export#20]
Hi,

Like others, I've been getting the Response Code: 500 error - I submitted the issue to the FitBit webAPI developers Forum: [api giving: Response code 500 (Internal Server Error) / Error id: A29EFF64:61D9_A92D826B:01BB_5A7CC3](https://community.fitbit.com/t5/Web-API-Development/api-giving-Response-code-500-Internal-Server-Error-Error-id-A29EFF64-61D9/m-p/2525905#M8767) - with the response from someone in the community being:

> Hi,
>
> The reason you are seeing this error is `max` is not a supported value for time period. Valid values are: >1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y as specified in https://dev.fitbit.com/build/reference/web-api/activity/

It seems like at some point this changed. Now that we know what's causing the issue, hopefully this can be updated/fixed so we can all get back to exporting!

**Comment by uncken** [comment]
I tried to commit to the master to replace timePeriod of 'max' with '1y' - but I guess I don't have permission to right now. Hopefully this change can be made and will fix the issues!

I think ideally the web-app might need to have a new option for 'baseDate' that can be changed from 'today' since it looks like we might need to run it more than once to get more than a year's worth of data.

**Comment by NickHeiner** [comment]
Ha, that's funny. Thanks for looking in to this.

Fitbit is wrong to return a `500` error code for what they're also saying is a malformed request, but I agree that it appears that they changed their API so my app doesn't work any more. I also agree that if `max` is gone, we'll need a different mechanism to get all data.

You're correct that you don't have permission to commit to `master`! However, you are free to modify this code and run it yourself locally. If you follow the (admittedly vague) instructions in the README, you can make the local environment work.

For a longer-term fix, I'll need to put a deeper solution in place.

**Comment by Amyunimus** [comment]
Is there a way to get it to return the last year's worth of data in the meantime?

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
