### ISSUE TITLE
Oops! Something broke!

### ISSUE THREAD

**Issue by mhuisingh** [NickHeiner/decomissioned-fitbit-export#24]
Here's the error:

{
  "message": "Response code 403 (Forbidden)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/sleep/minutesAsleep/date/today/max.json",
  "statusCode": 403,
  "statusMessage": "Forbidden",
  "requestUrl": "https://api.fitbit.com/1/user/-/sleep/minutesAsleep/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"insufficient_scope\",\"message\":\"This application does not have permission to access sleep data. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
