### ISSUE TITLE
422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by echarrod** [NickHeiner/decomissioned-fitbit-export#25]
I was downloading all of my data:

{
  "message": "Response code 422 (Unprocessable Entity)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"validation\",\"fieldName\":\"Request\",\"message\":\"The number of data points queried exceeds limit.\"}]}"
}

HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Spire42** [comment]
Just ran into the same thing after clicking “Download all available data as a csv”:

```
{
  "message": "Response code 422 (Unprocessable Entity)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"validation\",\"fieldName\":\"Request\",\"message\":\"The number of data points queried exceeds limit.\"}]}"
}
```
```
HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by RnSdr** [comment]
doesn't work

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
