### ISSUE TITLE
Trying to Export FitBit Data

### ISSUE THREAD

**Issue by sarahlutz** [NickHeiner/decomissioned-fitbit-export#27]
{
  "message": "Response code 422 (Unprocessable Entity)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesSedentary/date/today/max.json",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesSedentary/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"validation\",\"fieldName\":\"Request\",\"message\":\"The number of data points queried exceeds limit.\"}]}"
}
HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)

I just want to export my fitbit data so I can analyze it using Excel and JASP but this error message keeps coming up.

**Comment by NickHeiner** [comment]
Yep. The app isn't working right now. Some day, I would like to fix it.

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I'll be decommissioning this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
