### ISSUE TITLE
Error 422. The number of data points queried exceeds limit.

### ISSUE THREAD

**Issue by juergen-hollfelder** [NickHeiner/decomissioned-fitbit-export#28]
{
  "message": "Response code 422 (Unprocessable Entity)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesFairlyActive/date/today/max.json",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesFairlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"validation\",\"fieldName\":\"Request\",\"message\":\"The number of data points queried exceeds limit.\"}]}"
}
HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)

I think I have too much data for one call. Its since 2016.

**Comment by NickHeiner** [comment]
Fitbit now has a complete export on their site. I'll be decommissioning this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!

**Comment by Anatolik** [comment]
@NickHeiner the data provided by complete export is in different format (JSON instead of CSV). Garmin doesn't support JSON, so you project still makes perfect sense.

**Comment by NickHeiner** [comment]
Transforming JSON to CSV can be optimally done through a much simpler tool. And, I don't know which specific CSV formats people would need, so it would be impractical to offer a central app that was useful to a broad set of people.
